### ISSUE TITLE
Antiban?

### ISSUE THREAD

**Issue by JTD420** [Cr3atable/AntiBan#1]
Hi,

What exactly does this prevent? You mention themes from displaying the ban screen?

Which themes ban you for using them and how/why does this bypass that?

Thanks!

**Comment by Cr3atable** [comment]
Multiple themes use CSS to find your profile picture, which has your ID in it. Your Discord ID can be used to find out if you're a specific user. This plugin turns your profile picture into base64 and then replaces your profile picture, breaking any themes attempting to ban you. The base64 thing can be patched but even then there's other ways to work around theme banning.

The only themes that I've noticed ban anyone are themes that use "BlockBetterDocs" which block the website BetterDocs; they also ban the owner of BetterDocs from using them.
Use this plugin if you'd like to avoid being banned (if you're worried that you may be banned) from most themes.

**Comment by Cr3atable** [comment]
Clarified to user and user had no questions, closing now.
